#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC2034

MANAGED_REPO_IDS=()
declare -Ag MANAGED_REPO_DIRS=()
declare -Ag MANAGED_REPO_HTTPS_URLS=()
declare -Ag MANAGED_REPO_SSH_URLS=()
declare -Ag MANAGED_REPO_LABELS=()
declare -Ag MANAGED_REPO_ENVIRONMENT_FLAGS=()
declare -Ag MANAGED_REPO_CLONE_SUBMODULE_FLAGS=()
declare -Ag MANAGED_REPO_PREFERRED_TRANSPORTS=()

managed_repo_manifest_reset() {
  MANAGED_REPO_IDS=()
  MANAGED_REPO_DIRS=()
  MANAGED_REPO_HTTPS_URLS=()
  MANAGED_REPO_SSH_URLS=()
  MANAGED_REPO_LABELS=()
  MANAGED_REPO_ENVIRONMENT_FLAGS=()
  MANAGED_REPO_CLONE_SUBMODULE_FLAGS=()
  MANAGED_REPO_PREFERRED_TRANSPORTS=()
}
