#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BOOTSTRAP_LINT_FILE="$REPO_DIR/scripts/lint/bootstrap.sh"
RUNTIME_LINT_FILE="$REPO_DIR/scripts/lint/runtime.sh"

# shellcheck disable=SC1091
source "$REPO_DIR/scripts/bootstrap/bootstrap-modules.sh"
# shellcheck disable=SC1091
source "$REPO_DIR/scripts/lib/runtime-modules.sh"

usage() {
  cat <<'EOF'
Uso:
  bash scripts/build-lint-entrypoints.sh
  bash scripts/build-lint-entrypoints.sh --check
EOF
}

lint_source_directive_path() {
  local module_path="$1"

  printf '../%s\n' "${module_path#scripts/}"
}

generate_lint_entrypoint() {
  local array_name="$1"
  local skip_entrypoint="${2:-}"
  local module_path
  # shellcheck disable=SC2178
  declare -n lint_modules="$array_name"

  cat <<'EOF'
#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck source-path=SCRIPTDIR
# This file is generated by `bash scripts/build-lint-entrypoints.sh`.
# Do not edit it directly.
EOF

  for module_path in "${lint_modules[@]}"; do
    [[ "$module_path" == "$skip_entrypoint" ]] && continue
    printf '# shellcheck source=%s\n' "$(lint_source_directive_path "$module_path")"
  done

  cat <<'EOF'

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

EOF

  for module_path in "${lint_modules[@]}"; do
    [[ "$module_path" == "$skip_entrypoint" ]] && continue
    printf 'source "$REPO_DIR/%s"\n' "$module_path"
  done
}

write_or_check_lint_entrypoint() {
  local output_file="$1"
  local array_name="$2"
  local mode="${3:-}"
  local skip_entrypoint="${4:-}"
  local temp_file

  temp_file="$(mktemp)"
  generate_lint_entrypoint "$array_name" "$skip_entrypoint" >"$temp_file"

  if [[ "$mode" == "--check" ]]; then
    if ! cmp -s "$output_file" "$temp_file"; then
      printf 'Erro: %s está desatualizado. Rode bash scripts/build-lint-entrypoints.sh.\n' "${output_file#"$REPO_DIR"/}" >&2
      rm -f "$temp_file"
      exit 1
    fi
    rm -f "$temp_file"
    return 0
  fi

  mv "$temp_file" "$output_file"
  chmod 644 "$output_file"
}

write_or_check_lint_entrypoints() {
  local mode="${1:-}"

  # The bootstrap entrypoint runs main when sourced; dist/install.sh covers it.
  write_or_check_lint_entrypoint "$BOOTSTRAP_LINT_FILE" BOOTSTRAP_FRAGMENT_FILES "$mode" "scripts/bootstrap/entrypoint.sh"
  write_or_check_lint_entrypoint "$RUNTIME_LINT_FILE" RUNTIME_ENTRYPOINT_MODULE_FILES "$mode"
}

main() {
  case "${1:-}" in
    ""|--check)
      write_or_check_lint_entrypoints "${1:-}"
      ;;
    -h|--help)
      usage
      ;;
    *)
      printf 'Erro: opção desconhecida: %s\n' "${1:-}" >&2
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
