#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck source-path=SCRIPTDIR
# This file is generated by `bash scripts/build-lint-entrypoints.sh`.
# Do not edit it directly.
# shellcheck source=../lib/cli.sh
# shellcheck source=../lib/runtime-config.sh
# shellcheck source=../lib/invocation-context.sh
# shellcheck source=../lib/step-result.sh
# shellcheck source=../lib/ui/styles.sh
# shellcheck source=../lib/ui/logging.sh
# shellcheck source=../lib/ui/notice.sh
# shellcheck source=../lib/ui/summary-primitives.sh
# shellcheck source=../lib/pipeline.sh
# shellcheck source=../lib/step-registry.sh
# shellcheck source=../lib/step-manifest.sh
# shellcheck source=../lib/step-pipeline.sh
# shellcheck source=../lib/process.sh
# shellcheck source=../lib/locking.sh
# shellcheck source=../lib/env.sh
# shellcheck source=../lib/environment-validation.sh
# shellcheck source=../lib/ops/common.sh
# shellcheck source=../lib/ops/privilege.sh
# shellcheck source=../lib/ops/package.sh
# shellcheck source=../lib/ops/filesystem.sh
# shellcheck source=../lib/ops/git.sh
# shellcheck source=../lib/ops/github.sh
# shellcheck source=../lib/ops/node.sh
# shellcheck source=../lib/ops/ssh.sh
# shellcheck source=../lib/ops/systemd.sh
# shellcheck source=../lib/repo/manifest/store.sh
# shellcheck source=../lib/repo/manifest/registration.sh
# shellcheck source=../lib/repo/manifest/definitions.sh
# shellcheck source=../lib/repo/manifest/queries.sh
# shellcheck source=../lib/repo/origin/status.sh
# shellcheck source=../lib/repo/origin/remote.sh
# shellcheck source=../lib/repo/origin/transport.sh
# shellcheck source=../lib/repo/origin/managed.sh
# shellcheck source=../lib/repo/relocation.sh
# shellcheck source=../lib/repo/sync.sh
# shellcheck source=../bootstrap/repo-sync.sh
# shellcheck source=../bootstrap/config.sh
# shellcheck source=../bootstrap/steps/system.sh
# shellcheck source=../bootstrap/steps/packages.sh
# shellcheck source=../bootstrap/steps/repo.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$REPO_DIR/scripts/lib/cli.sh"
source "$REPO_DIR/scripts/lib/runtime-config.sh"
source "$REPO_DIR/scripts/lib/invocation-context.sh"
source "$REPO_DIR/scripts/lib/step-result.sh"
source "$REPO_DIR/scripts/lib/ui/styles.sh"
source "$REPO_DIR/scripts/lib/ui/logging.sh"
source "$REPO_DIR/scripts/lib/ui/notice.sh"
source "$REPO_DIR/scripts/lib/ui/summary-primitives.sh"
source "$REPO_DIR/scripts/lib/pipeline.sh"
source "$REPO_DIR/scripts/lib/step-registry.sh"
source "$REPO_DIR/scripts/lib/step-manifest.sh"
source "$REPO_DIR/scripts/lib/step-pipeline.sh"
source "$REPO_DIR/scripts/lib/process.sh"
source "$REPO_DIR/scripts/lib/locking.sh"
source "$REPO_DIR/scripts/lib/env.sh"
source "$REPO_DIR/scripts/lib/environment-validation.sh"
source "$REPO_DIR/scripts/lib/ops/common.sh"
source "$REPO_DIR/scripts/lib/ops/privilege.sh"
source "$REPO_DIR/scripts/lib/ops/package.sh"
source "$REPO_DIR/scripts/lib/ops/filesystem.sh"
source "$REPO_DIR/scripts/lib/ops/git.sh"
source "$REPO_DIR/scripts/lib/ops/github.sh"
source "$REPO_DIR/scripts/lib/ops/node.sh"
source "$REPO_DIR/scripts/lib/ops/ssh.sh"
source "$REPO_DIR/scripts/lib/ops/systemd.sh"
source "$REPO_DIR/scripts/lib/repo/manifest/store.sh"
source "$REPO_DIR/scripts/lib/repo/manifest/registration.sh"
source "$REPO_DIR/scripts/lib/repo/manifest/definitions.sh"
source "$REPO_DIR/scripts/lib/repo/manifest/queries.sh"
source "$REPO_DIR/scripts/lib/repo/origin/status.sh"
source "$REPO_DIR/scripts/lib/repo/origin/remote.sh"
source "$REPO_DIR/scripts/lib/repo/origin/transport.sh"
source "$REPO_DIR/scripts/lib/repo/origin/managed.sh"
source "$REPO_DIR/scripts/lib/repo/relocation.sh"
source "$REPO_DIR/scripts/lib/repo/sync.sh"
source "$REPO_DIR/scripts/bootstrap/repo-sync.sh"
source "$REPO_DIR/scripts/bootstrap/config.sh"
source "$REPO_DIR/scripts/bootstrap/steps/system.sh"
source "$REPO_DIR/scripts/bootstrap/steps/packages.sh"
source "$REPO_DIR/scripts/bootstrap/steps/repo.sh"
